var hierarchy =
[
    [ "com.tuya.smart.camera.ipccamerasdk.bean.CameraInfoBean.AudioAttributes", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1bean_1_1_camera_info_bean_1_1_audio_attributes.html", null ],
    [ "com.tuya.smart.android.camera.sdk.annotation.BuildForInside", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1annotation_1_1_build_for_inside.html", null ],
    [ "com.tuya.smart.android.camera.sdk.annotation.BuildForOpen", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1annotation_1_1_build_for_open.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.utils.CameraConstant", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1utils_1_1_camera_constant.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.bean.CameraInfoBean", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1bean_1_1_camera_info_bean.html", null ],
    [ "com.tuya.smart.android.camera.sdk.bean.CameraMessageClassifyBean", "classcom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1bean_1_1_camera_message_classify_bean.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.bean.ConfigCameraBean", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1bean_1_1_config_camera_bean.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.utils.P2PConstant.ErrorCode", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1utils_1_1_p2_p_constant_1_1_error_code.html", null ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.FileDownloadFinishCallBack", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_file_download_finish_call_back.html", null ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.FileDownLoadProgressCallBack", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_file_down_load_progress_call_back.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.bean.CameraInfoBean.FishEyeClarity", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1bean_1_1_camera_info_bean_1_1_fish_eye_clarity.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.utils.HomeProxyUtil", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1utils_1_1_home_proxy_util.html", null ],
    [ "com.tuya.smart.camera.middleware.p2p.ICameraConfig", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1middleware_1_1p2p_1_1_i_camera_config.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ICameraConfigInfo", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_camera_config_info.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ICameraFactory", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_camera_factory.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.p2p.ICameraP2P< T >", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1p2p_1_1_i_camera_p2_p.html", [
      [ "com.tuya.smart.camera.ipccamerasdk.p2p.AbsTutkCameraP2P", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1p2p_1_1_abs_tutk_camera_p2_p.html", null ]
    ] ],
    [ "com.tuya.smart.ipc.panel.api.IIpcDiffPlugin", "interfacecom_1_1tuya_1_1smart_1_1ipc_1_1panel_1_1api_1_1_i_ipc_diff_plugin.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.monitor.IMonitorView< T >", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1monitor_1_1_i_monitor_view.html", [
      [ "com.tuya.smart.camera.ipccamerasdk.monitor.AbsMonitorViewProxy", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1monitor_1_1_abs_monitor_view_proxy.html", null ]
    ] ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.IRegistorIOTCListener", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_i_registor_i_o_t_c_listener.html", null ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.IRegistorTalkListener", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_i_registor_talk_listener.html", null ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.ISpeakerEchoProcessor", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_i_speaker_echo_processor.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCCloud", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_cloud.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCCore", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_core.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCCount", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_count.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCDoorbell", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_doorbell.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCDoorBellManager", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_door_bell_manager.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCExtPlugin", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_ext_plugin.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCHomeProxy", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_home_proxy.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCInside", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_inside.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCMsg", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_msg.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCMsgManager", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_msg_manager.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCMsgPlugin", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_msg_plugin.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCPlugin", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_plugin.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaIPCTool", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_i_p_c_tool.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.ITuyaLibLoader", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1_i_tuya_lib_loader.html", null ],
    [ "com.tuya.smart.p2p.api.ITuyaP2P", "interfacecom_1_1tuya_1_1smart_1_1p2p_1_1api_1_1_i_tuya_p2_p.html", null ],
    [ "com.tuya.smart.android.camera.sdk.api.ITuyaP2pPlugin", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1api_1_1_i_tuya_p2p_plugin.html", null ],
    [ "com.tuya.smart.camera.middleware.p2p.ITuyaSmartCameraP2P< T >", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1middleware_1_1p2p_1_1_i_tuya_smart_camera_p2_p.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.cloud.ITYCloudCamera", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1cloud_1_1_i_t_y_cloud_camera.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.msgvideo.ITYCloudVideo", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1msgvideo_1_1_i_t_y_cloud_video.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.monitor.MonitorClickCallback", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1monitor_1_1_monitor_click_callback.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.bean.MonthDays", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1bean_1_1_month_days.html", null ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.OnCameraGestureListener", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_on_camera_gesture_listener.html", null ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.OnP2PCameraListener", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_on_p2_p_camera_listener.html", [
      [ "com.tuya.smart.camera.camerasdk.typlayer.callback.AbsP2pCameraListener", "classcom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_abs_p2p_camera_listener.html", null ]
    ] ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.OnRenderDirectionCallback", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_on_render_direction_callback.html", null ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.OnRenderZoomListener", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_on_render_zoom_listener.html", null ],
    [ "com.tuya.smart.android.camera.sdk.annotation.OpenApi", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1annotation_1_1_open_api.html", null ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.OperationCallBack", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_operation_call_back.html", null ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.OperationDelegateCallBack", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_operation_delegate_call_back.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.bean.CameraInfoBean.P2pConfig", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1bean_1_1_camera_info_bean_1_1_p2p_config.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.utils.P2PConstant", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1utils_1_1_p2_p_constant.html", null ],
    [ "com.tuya.smart.camera.annotation.PlayBackSpeed", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1annotation_1_1_play_back_speed.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.p2p.ICameraP2P< T >.PLAYMODE", "enumcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1p2p_1_1_i_camera_p2_p_1_1_p_l_a_y_m_o_d_e.html", null ],
    [ "com.tuya.smart.camera.camerasdk.typlayer.callback.ProgressCallBack", "interfacecom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1typlayer_1_1callback_1_1_progress_call_back.html", null ],
    [ "com.tuya.smart.android.camera.sdk.callback.ProgressCallback", "interfacecom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1callback_1_1_progress_callback.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.utils.P2PConstant.REQUEST_ID", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1utils_1_1_p2_p_constant_1_1_r_e_q_u_e_s_t___i_d.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.monitor.RockerAvailableDirection", "enumcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1monitor_1_1_rocker_available_direction.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.utils.P2PConstant.SuccessCode", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1utils_1_1_p2_p_constant_1_1_success_code.html", null ],
    [ "com.tuya.smart.camera.ipccamerasdk.p2p.ICameraP2P< T >.TagBean", "classcom_1_1tuya_1_1smart_1_1camera_1_1ipccamerasdk_1_1p2p_1_1_i_camera_p2_p_1_1_tag_bean.html", null ],
    [ "com.tuya.smart.camera.camerasdk.bean.TuyaIOTCameraInfo", "classcom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1bean_1_1_tuya_i_o_t_camera_info.html", null ],
    [ "com.tuya.smart.android.camera.sdk.constant.TuyaIPCConstant", "classcom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1constant_1_1_tuya_i_p_c_constant.html", null ],
    [ "com.tuya.smart.android.camera.sdk.TuyaIPCSdk", "classcom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1_tuya_i_p_c_sdk.html", null ],
    [ "com.tuya.smart.android.camera.sdk.callback.TuyaSmartDoorBellObserver", "classcom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1callback_1_1_tuya_smart_door_bell_observer.html", null ],
    [ "com.tuya.smart.android.camera.sdk.bean.TYDoorBellCallModel", "classcom_1_1tuya_1_1smart_1_1android_1_1camera_1_1sdk_1_1bean_1_1_t_y_door_bell_call_model.html", null ],
    [ "Parcelable", null, [
      [ "com.tuya.smart.camera.camerasdk.bean.TuyaAudioFrameInfo", "classcom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1bean_1_1_tuya_audio_frame_info.html", null ],
      [ "com.tuya.smart.camera.camerasdk.bean.TuyaVideoFrameInfo", "classcom_1_1tuya_1_1smart_1_1camera_1_1camerasdk_1_1bean_1_1_tuya_video_frame_info.html", null ]
    ] ]
];